apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-ui
   spec:
     replicas: "{{ todo_app_ui_replica_count }}"
     selector:
      matchLabels:
         app: todo-app-ui
     template:
       metadata:
         labels:
           app: todo-app-ui
       spec:
         containers:
           - name: todo-app-ui
             image: 772835013a82:latest
             ports:
               - containerPort: 80
